# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trace.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'trace.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btrace.proto\x12\x0bnerrf.trace\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd7\x02\n\x05\x45vent\x12&\n\x02ts\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0b\n\x03pid\x18\x02 \x01(\r\x12\x0b\n\x03tid\x18\x03 \x01(\r\x12\x0c\n\x04\x63omm\x18\x04 \x01(\t\x12\x0f\n\x07syscall\x18\x05 \x01(\t\x12\x0c\n\x04path\x18\x06 \x01(\t\x12\x10\n\x08new_path\x18\x07 \x01(\t\x12+\n\x05\x66lags\x18\x08 \x01(\x0e\x32\x1c.nerrf.trace.Event.OpenFlags\x12\x0f\n\x07ret_val\x18\t \x01(\x12\x12\r\n\x05\x62ytes\x18\n \x01(\x04\x12\r\n\x05inode\x18\x0b \x01(\t\x12\x0c\n\x04mode\x18\x0c \x01(\r\x12\x0b\n\x03uid\x18\r \x01(\x04\x12\x0b\n\x03gid\x18\x0e \x01(\x04\x12\x14\n\x0c\x64\x65pendencies\x18\x0f \x03(\t\"3\n\tOpenFlags\x12\x0c\n\x08O_RDONLY\x10\x00\x12\x0c\n\x08O_WRONLY\x10\x01\x12\n\n\x06O_RDWR\x10\x02\"0\n\nEventBatch\x12\"\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x12.nerrf.trace.EventB\rZ\x0bnerrf/traceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trace_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013nerrf/trace'
  _globals['_EVENT']._serialized_start=62
  _globals['_EVENT']._serialized_end=405
  _globals['_EVENT_OPENFLAGS']._serialized_start=354
  _globals['_EVENT_OPENFLAGS']._serialized_end=405
  _globals['_EVENTBATCH']._serialized_start=407
  _globals['_EVENTBATCH']._serialized_end=455
# @@protoc_insertion_point(module_scope)
